Переписал весь проект на NGRX
RYAZHAPOVILNUR/mentoring-first-task pull request #102
Opened 2024-12-22 17:01 UTC by anuaralpiyev

telegram: Anuar
https://t.me/the_majik

2024-12-28 16:19 UTC, asylbekovkairat requested changes

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/app.component.ts
> +import {HeaderComponent} from "./component/header/header.component";
слетело форматирование, установите VsCode расширение prettier и отформатируйте код

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/app.config.ts
> +import {provideAnimationsAsync} from '@angular/platform-browser/animations/async';
форматировка кода нужна

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/directives/color-basket.directive.ts
> +  colorOne: string = '';
хорошей практикой является ставить модификаторы доступа private или public и readonly если переменная будет использовать только для чтения и не будет менятся

Изучаите про private public и readonly и примените везде где можно

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/directives/shadow.directive.ts
> +    shadowCards: string = '';
модификаторы доступа (см. выше)

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/footer/footer.component.ts
> +
зачем пустая строка

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/guards/auth.guard.ts
> +    if (userService.isAdmin) {
`if (userService.isAdmin) {
        return true;
    } else {
        return router.navigate(['users']).then((result: boolean) => {
            return false;
        })
    }`
    этот код можно сократить вот так 
    
`if (userService.isAdmin) return true;
return router.navigate(['users']).then((result: boolean) => false)`

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +const showCatalog: (showText: string) => string = (showText: string) => showText;
такие функции лучше выносить в отдельный файл utils.ts и оттуда делать import

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +    title: string = 'mentoring-first-task';
модификаторы доступа

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +    public showCatalog: boolean = false;
readonly можно поставить если да, то поставьте, если нет сделайте resolve conversation

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +
лишняя строка

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +                return undefined;
вы как разработчик, не должны возвращать undefined, лучше возвращать null

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +            if (result === 'admin') {
попробуйте сократить код для вашей конструкции if else

2024-12-28 16:19 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +                return undefined;
undefined нельзя возвращать. Undefined возвращает только программа

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +        dialogRef.afterClosed().subscribe((result: string) => {
добавьте отписку

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/homepage/homepage.component.ts
> +  showImage: boolean = true;
public readonly

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/pipes/custom-current-date-time.pipe.ts
> +        switch (format) {
использовать switch не лучшая идея, лучше использовать объект 

`dateFormatOptions = {
    short : {dateStyle: 'short', timeStyle: 'short'},
    long: {dateStyle: 'long', timeStyle: 'long'}
}`

и использовать как 
`return dateFormatOptions[format] ?? {dateStyle: 'medium', timeStyle: 'medium'}`

если не понятно, можем созвонится на 15 минут

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/pipes/remove-dashes.pipe.ts
> +    transform(value: string | undefined): string | undefined {
чтобы не указывать в типах undefined можно просто сделать поле optional
`value?: string`

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/pipes/remove-dashes.pipe.ts
> +        if (!value) return '';
круто написали условие, но предлагаю добавить пустую строку перед return

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/user.service.ts
> +    constructor(private router: Router) {
для инжектирования используйте inject

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/user.service.ts
> +    // public get isAdmin() {
удалите комментарий

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/user.service.ts
> +        if (this.userSubject$.value) {
визуально сократите условие

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users-api.service.ts
> +
лишняя пустая строка

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +    // public setUsers(users: IUser[]) {
удалите комментарий

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +    private readonly usersApiService: UsersApiService = inject(UsersApiService);
инжектирование зависимостей должно быть в самом верху перед usersSubject$

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +    // создание юзера
удалите комментарий, по названию метода понятно, что создание юзера )

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +    // public createUser(user: IUser): void {
удалите комментарий

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +    // удаление юзера
удалите везде комментарии

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +
лишняя строка

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +        if (findUser) {
можно написать как 
`if (findUser) this.setUsers(newArrayUsers);`

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +    // deleteUser(id: number): void {
удалите комментарий

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-button/create-user-button.component.ts
> +    @Output()
пустой output? удалить можно

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-button/create-user-button.component.ts
> +
лишние пустые строки

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-button/create-user-button.component.ts
> +        dialogRef.afterClosed().subscribe((result: IUserCreate) => {
добавьте отписку

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-dialog/create-user-dialog.component.scss
> +  text-align: center; /* Центрирование для inline-блочных элементов */
удалите комментарии

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-dialog/create-user-dialog.component.ts
> +        dialogRef.afterClosed().subscribe((result: IUserCreate) => {
отписка

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-form/create-user-form.component.ts
> +    // public matcher: MyErrorEstateMatcher = new MyErrorEstateMatcher();
удалите комментарий

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/edit-user-form/edit-user-form.component.ts
> +
удалите лишние пустые строки между переменными

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/user-card/user-card.component.ts
> +    @Output()
outout и input должны быть в самом верху

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/user-card/user-card.component.ts
> +    // public onDeleteUser(userId: number) {
комментарий

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/user-card/user-card.component.ts
> +        dialogRef.afterClosed().subscribe((result: boolean | undefined) => {
отписка

2024-12-28 16:19 UTC, asylbekovkairat commented on src/app/component/users-list/users-list.component.ts
> +
удалите пустую строку

2024-12-30 15:27 UTC, asylbekovkairat requested changes
Некоторые комменты не исправлены, изучите как делать отписки в Angular 
https://stackoverflow.com/questions/38008334/angular-rxjs-when-should-i-unsubscribe-from-subscription

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/guards/auth.guard.ts
> +    return userService.isAdmin ? true : router.navigate(['users']).then((result: boolean): boolean => false);
условие после return можно сократить как
`return userService.isAdmin ?? router.navigate(['users']).then((result: boolean): boolean => false);`

Референс https://learn.javascript.ru/nullish-operators

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +// const showCatalog: (showText: string) => string = (showText: string) => showText;
Удалите комментарий

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +    (item: string) => {
можно написать так `(item: string) => item.toUpperCase()`

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +    public title: string = 'mentoring-first-task';
если можно поставить readonly, то лучше поставьте

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +    public readonly dialog: MatDialog = inject(MatDialog);
MatDialog точно public?

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +    public readonly userService: UserService = inject(UserService);
userService точно public?

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +
удалите пустую строку

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +        dialogRef.afterClosed().pipe(take(1)).subscribe((result: string): void | null => {
добавьте отписку

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +        dialogRef.afterClosed().pipe(take(1)).subscribe((result: string) => {
добавьте отписку

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/homepage/homepage.component.ts
> +    public showImage: boolean = true;
можно поставить readonly

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/logout/logout.component.ts
> +export class LogoutComponent {
`export class LogoutComponent {}`

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/pipes/custom- upper-case.pipe.ts
> +
лишняя строка

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/pipes/custom- upper-case.pipe.ts
> +
лишняя строка

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/pipes/remove-dashes.pipe.ts
> +
лишняя строка

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +            (user: IUser) => user.id !== userId); // Условие: оставляем только тех пользователей, чей id не равен userId
удалите комментарии лишние

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/services/users.service.ts
> +            (user: IUser) => user.id === userId); // Условие: ищем пользователя с id равным userId
удалите комментарии лишние

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-button/create-user-button.component.ts
> +        dialogRef.afterClosed().pipe(take(1)).subscribe((result: IUserCreate) => {
отписку добавьте

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-dialog/create-user-dialog.component.ts
> +
удалите лишнюю строку

2024-12-30 15:27 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-dialog/create-user-dialog.component.ts
> +        dialogRef.afterClosed().pipe(take(1)).subscribe((result: IUserCreate) => {
добавьте отписку

2024-12-30 18:07 UTC, anuaralpiyev commented on src/app/component/homepage/homepage.component.ts
> +    public showImage: boolean = true;
когда ставлю readonly его html начинается ругаться

2025-01-03 04:09 UTC, asylbekovkairat requested changes

2025-01-03 04:09 UTC, kairat-asylbekov-engineer commented on src/app/app.config.ts
> +import {provideAnimationsAsync} from '@angular/platform-browser/animations/async';
https://youtu.be/cJDTji4eHSU?si=u8MxixM-eIlFN9rt посмотрите

2025-01-03 04:09 UTC, kairat-asylbekov-engineer commented on src/app/component/admin/admin.component.ts
> +export class AdminComponent {
export class AdminComponent {}

2025-01-03 04:09 UTC, kairat-asylbekov-engineer commented on src/app/component/auth/auth.component.ts
> +}
export class AuthComponent {}

2025-01-03 04:09 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +const menuItems: string[] = ['Каталог', 'Запчасти', ' Интерьер', ' Стиль', 'Партнеры'];
эти данные нужно вынести в отдельный файл и импортировать оттуда, потому что такие константы должны храниться отдельно от бизнес логики.

2025-01-03 04:09 UTC, kairat-asylbekov-engineer commented on src/app/component/header/header.component.ts
> +const upperCaseMenuItems: string[] = menuItems.map(
для таких задач, лучше писать переиспользуемые функции, прокидывать туда массив, и получать от него обработанные/результативные  данные

2025-01-03 04:09 UTC, asylbekovkairat commented on src/app/component/header/header.component.ts
> +    public readonly headerItemMain: string = 'Главная';
инициализацию полей класса пишите сверху компоненты. Там где inject

2025-01-03 04:09 UTC, asylbekovkairat commented on src/app/component/homepage/homepage.component.ts
> +    public showImage: boolean = true;
> когда ставлю readonly html компонент ругаться

окей, тогда гуд 👍

2025-01-03 04:09 UTC, asylbekovkairat commented on src/app/component/pipes/remove-dashes.pipe.ts
> +        if (!value) return '';
> круто написали условие, но предлагаю добавить пустую строку перед return

не исправлено

2025-01-03 04:09 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-button/create-user-button.component.ts
> +
лишняя пустая строка 31

2025-01-03 04:09 UTC, asylbekovkairat commented on src/app/component/users-list/user-card/user-card.component.ts
> +
лишняя пустая строка

2025-01-03 04:09 UTC, asylbekovkairat commented on src/styles.scss
> +  width: 100%; /* Занимает всю ширину экрана */
удалите комменты

2025-01-04 10:45 UTC, asylbekovkairat requested changes

2025-01-04 10:45 UTC, asylbekovkairat commented on src/app/component/admin/admin.component.scss
удалите пустой файл если он не нужен

2025-01-04 10:45 UTC, asylbekovkairat commented on src/app/component/services/user.service.ts
> +    private readonly router: Router = inject(Router)
inject должны быть выше userSubject$

2025-01-04 10:45 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-button/create-user-button.component.ts
> +
удалите пустую строку

2025-01-04 10:45 UTC, asylbekovkairat commented on src/app/component/users-list/edit-user-form/edit-user-form.component.ts
> +
удалите пустую строку

2025-01-07 05:45 UTC, asylbekovkairat requested changes

2025-01-07 05:45 UTC, asylbekovkairat commented on src/app/app.component.ts
> +  title: string = 'mentoring-first-project';
модификаторы доступа и readonly можно добавить

2025-01-07 05:45 UTC, asylbekovkairat commented on src/app/component/users-list/create-user-form/create-user-form.component.ts
> +
удалите пустую строку

2025-01-08 15:59 UTC, asylbekovkairat approved these changes

2025-01-09 10:47 UTC, closed without merging