Сделал задание для Джунов без Ngrx (Alim)
RYAZHAPOVILNUR/mentoring-first-task pull request #16
Opened 2024-05-22 19:46 UTC by Vampire829

2024-05-29 16:41 UTC, RYAZHAPOVILNUR requested changes

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/create-edit-user/create-edit-user.component.html
> +
лишние пустые строки

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/create-edit-user/create-edit-user.component.ts
> +    console.log(this.data);
убрать console.log

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/create-edit-user/create-edit-user.component.ts
> +    console.log(this.newForm.value);
убрать console.log

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/create-edit-user/create-edit-user.component.ts
> +}else{
форматирование страдает

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/create-edit-user/create-edit-user.component.ts
> +  public saveUser() {
такой код не принимается

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/service/user.service.ts
> +
лишние пустые строки

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/service/user.service.ts
> +    }else{
форматирование

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/service/user.service.ts
> +
пустые строки

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/service/user.service.ts
> +    console.log(
убрать console.log

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/service/user.service.ts
> +    const id = of(this.getUsers).pipe(
не нужно создавать константу

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/service/userApiService.ts
> + constructor(private http: HttpClient){
форматирование

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/service/userApiService.ts
> +private Url = 'https://jsonplaceholder.typicode.com/users';
нужно с маленькой буквы

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/user-card/user-card.component.ts
> +console.log(this.user.name)
консоль

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/user-card/user-card.component.ts
> +      this.remove.emit(this.user.id)
форматирование

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/user-list/user-list.component.ts
> +public openDialog(user?: User){
форматирование

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/user-list/user-list.component.ts
> +  data: {
форматирование

2024-05-29 16:41 UTC, RYAZHAPOVILNUR commented on src/app/user-list/user-list.component.ts
> +
пустые строки

2024-06-02 04:41 UTC, Vampire829 commented on src/app/create-edit-user/create-edit-user.component.ts
> +  public saveUser() {
Можно узнать почему?

2024-07-18 14:22 UTC, closed without merging