джуновское задание
RYAZHAPOVILNUR/mentoring-first-task pull request #2
Opened 2024-04-24 13:05 UTC by StarcevAlexander

2024-05-03 10:02 UTC, RYAZHAPOVILNUR requested changes

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/app.component.ts
> +  imports: [RouterOutlet, CommonModule, RouterLink, RouterLinkActive, HttpClientModule, NavigationComponent, HeaderComponent, FooterComponent, FormsModule, ReactiveFormsModule],
очень длинно, надо бы разнести по разным строкам

[
  RouterOutlet,
  CommonModule
  ... и тд
]

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/components/user-card/user-card.component.ts
> +    id: number): void {
форматирование поехало

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/components/user-list/user-list.component.ts
> +  constructor(
сначала поля класса, а ниже конструктор

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/components/user-list/user-list.component.ts
> +    redact: boolean): void {
форматирование поехало

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/components/users-list-modal-window/users-list-modal-window.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: { redact: boolean, id: number }) { }
форматирование поехало

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/components/users-list-modal-window/users-list-modal-window.component.ts
> +    "userId": new FormControl("", Validators.required),
кавычки не нужны

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/components/users-list-modal-window/users-list-modal-window.component.ts
> +      if (this.data.redact) {
что значит redact?

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/components/users-list-modal-window/users-list-modal-window.component.ts
> +          email: this.myForm.value.userEmail as string,
зачем везде приводить к типам через "as", в ангуляре есть типизированные формы

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/core/services/master-users-api-service.service.ts
> +    return this.http.get<UsersType[]>('https://jsonplaceholder.typicode.com/users')
лучше бы вынести адрес бэка в переменную окружения

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/core/services/ngrxlocalstorage.service.ts
> +
лишняя пустая строка

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/core/services/ngrxlocalstorage.service.ts
> +    }
форматирование поехало

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/core/services/ngrxlocalstorage.service.ts
> +    }
форматирование поехало

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/core/services/ngrxlocalstorage.service.ts
> +      {
лишние фигурные скобки

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/core/state/users/users.effects.ts
> +    _loadUsers = createEffect(() =>
нижнее подчеркивание ни к чему, так делают с приватными полями и методами

можно было сделать эффекты функциональными и вообще не создавать класс

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/core/state/users/users.reducer.ts
> +const _UserReducer = createReducer(userState,
константы с маленькой буквы, и подчеркивание не нужно

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/pages/home/home.component.ts
> +  async LoadInitialData() {
async убрать

метод назвать с маленькой буквы

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/pages/home/home.component.ts
> +    await this.store.dispatch(loadUsers())
await убрать, это не асинхронный код

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/pages/home/home.component.ts
> +      alert('тут могла быть ваша реклама')
не реализована логика

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/pages/home/home.component.ts
> +    alert('тут могла быть ваша реклама')
не реализована логика

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/shared/component/header/header.component.scss
> +  }
не хватает пустой строки

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented on src/app/shared/component/navigation/navigation.component.html
> +        <li>
форматирование в этом файле с 4 пробелами, в других файлах с двумя, нужно единообразие

2024-05-03 10:02 UTC, RYAZHAPOVILNUR commented
на доработку

2024-05-09 03:51 UTC, StarcevAlexander commented on src/app/core/services/ngrxlocalstorage.service.ts
> +    }
приттер так видит и никак иначе. как правильно?

2024-05-09 04:12 UTC, StarcevAlexander commented on src/app/pages/home/home.component.ts
> +      alert('тут могла быть ваша реклама')
это элемент самостоятельного/учебного/тренировочного кода, он не имеет отношения к заданию для новичков. хотел показать что разобрался с пагинацией и прочим

2024-05-09 04:12 UTC, StarcevAlexander commented on src/app/pages/home/home.component.ts
> +    alert('тут могла быть ваша реклама')
это элемент самостоятельного/учебного/тренировочного кода, он не имеет отношения к заданию для новичков. хотел показать что разобрался с пагинацией и прочим

2024-05-09 04:22 UTC, StarcevAlexander commented on src/app/shared/component/navigation/navigation.component.html
> +        <li>
изменил настройки vc code, перепровелил все компоненты

2024-05-09 04:24 UTC, StarcevAlexander commented
спасибо за обратную связь. да, не без косяков, но в целом всё удалось. большинство ошибок изза малой насмотренности и недостатка опыта. работаем дальше

2024-05-09 04:55 UTC, StarcevAlexander commented on src/app/components/users-list-modal-window/users-list-modal-window.component.ts
> +      if (this.data.redact) {
значит что пользователь открывает модальное окно для редактирования, а иначе в нём отображаются поля для ввода данных нового пользователя. по заданию нужно было реализовать это в одном компоненте, который в зависимости от входных данных меняет поведение. я передаю то или иное булевое состояние переменной редакт при вызове метода, создающего модальное окно и при создании окна проверяю состояние переменнной редакт. если хочу добавить нового пользователя - редакт ложный, если отредактировать - трушный.

2024-05-09 04:55 UTC, StarcevAlexander commented on src/app/components/users-list-modal-window/users-list-modal-window.component.ts
> +          email: this.myForm.value.userEmail as string,
+++

2024-05-09 04:56 UTC, StarcevAlexander commented on src/app/core/services/ngrxlocalstorage.service.ts
> +
правильно ведь понял, что нужно просто написать в одну строку?

2024-05-09 04:58 UTC, StarcevAlexander commented on src/app/core/services/ngrxlocalstorage.service.ts
> +    }
вообще убрал кавычки

2024-05-09 05:07 UTC, StarcevAlexander commented on src/app/pages/home/home.component.ts
> +  async LoadInitialData() {
тогда тут пагинация отваливается. не смог c разбегу понять в чём дело, скорее всего angular material только так и видит.

2024-05-09 05:07 UTC, StarcevAlexander commented on src/app/pages/home/home.component.ts
> +    await this.store.dispatch(loadUsers())
тогда тут пагинация отваливается. не смог c разбегу понять в чём дело, скорее всего angular material только так и видит.

2024-06-03 02:58 UTC, closed without merging