first commit with NGRX
RYAZHAPOVILNUR/mentoring-first-task pull request #34
Opened 2024-06-30 10:40 UTC by Bolatzhan

С NGRX

2024-07-07 23:59 UTC, saidazagirova approved these changes

2024-07-08 06:55 UTC, pynhaXD requested changes

2024-07-08 06:55 UTC, SemenovRoman12 commented on src/app/components/create-edit-user/create-edit-user.component.ts
> +  onNoClick(): void {
Как говорил Ильнур у методов лучше указывать модификаторы доступа

2024-07-08 06:55 UTC, pynhaXD commented on src/app/components/users-list/users-list.component.ts
> +  constructor(private store: Store<AppState>, private dialog: MatDialog) {
Лучше использовать функцию inject() например:
private readonly store = inject(Store);

2024-07-08 06:55 UTC, pynhaXD commented on src/app/components/users-list/users-list.component.ts
> +    this.loading$ = this.store.pipe(select(selectUsersLoading));
Вообще всю ngrx логику желательно вынести в файл users.facade.ts (патерн проектирования) где там ты за инжектишь store и обернешь диспатч экшинов в методы, а селекторы в поля класса.
Это нужно для того чтобы компонент не знал какой стейт менджер ты используешь.

2024-07-08 06:55 UTC, pynhaXD commented on src/app/models/user.ts
> +
На сколько я знаю файлы в папке models нужно именовать так - name.model.ts. Чтобы было понятно что это модель данных

2024-07-08 06:55 UTC, pynhaXD commented on src/app/components/create-edit-user/create-edit-user.component.html
> +      <mat-error *ngIf="userForm.get('name')?.invalid">
Не понятно для чего проверки  в <mat-error> если ты в форм билдере уже стоит валидатор Validators.required.

2024-07-08 06:55 UTC, pynhaXD commented on src/app/services/users-api.service.ts
> +  getUsers(): Observable<User[]> {
В users-api.service нужно создать все методы взаимодействия я с юзером. Например deleteUser в котором будет this.http.delete ...

2024-07-08 06:55 UTC, pynhaXD commented on src/app/store/users/users.reducer.ts
> +
Лучше определять интерфейс и начальные значения стейта в этом файле (по крайней мере так в проекте менторинга).

2024-07-08 06:55 UTC, pynhaXD commented on src/app/store/users/users.effects.ts
> +  );
Ну и тут соответственно было бы 4 эффекта после реализации всех методов в users api service

2024-07-08 06:55 UTC, pynhaXD commented on src/app/services/local-storage.service.ts
> +
Когда мы переходим на ngrx мы избавляемся от local storage сервиса

2024-07-08 06:55 UTC, pynhaXD commented on src/app/services/users.service.ts
> +  private usersSubject$ = new BehaviorSubject<User[]>([]);
Тут не понятно почему реализована логика хранения данных как мы писали на сервисах, хотя ты использовал ngrx и должен обновлять поле users в стейте

2024-07-08 06:55 UTC, pynhaXD commented on src/app/store/users/users.actions.ts
> +
нужно ко всем экшинам добавить успешное и провальное выполнение

2024-07-08 06:55 UTC, pynhaXD commented on src/app/store/users/users.effects.ts
> +      mergeMap(() =>
Насколько я знаю лучше использовать switchMap вместо mergeMap так как switchMap отписывается от предыдущего потока (могу ошибаться).

2024-07-10 01:05 UTC, RYAZHAPOVILNUR commented on src/app/components/users-list/users-list.component.ts
> +    this.loading$ = this.store.pipe(select(selectUsersLoading));
> Вообще всю ngrx логику желательно вынести в файл users.facade.ts (патерн проектирования) где там ты за инжектишь store и обернешь диспатч экшинов в методы, а селекторы в поля класса. Это нужно для того чтобы компонент не знал какой стейт менджер ты используешь.

в задаче для новичков это не обязательно

2024-07-10 01:07 UTC, RYAZHAPOVILNUR commented on src/app/components/create-edit-user/create-edit-user.component.html
> +      <mat-error *ngIf="userForm.get('name')?.invalid">
invalid даст результирующее по всем валидаторам

2024-07-10 01:08 UTC, RYAZHAPOVILNUR commented on src/app/store/users/users.effects.ts
> +      mergeMap(() =>
вообще - да

тут просто такие кейсы что сам экшен срабатывает гарантированно только 1 раз и все, поэтому разницы нее будет

2024-07-10 01:39 UTC, RYAZHAPOVILNUR approved these changes

2024-07-10 01:39 UTC, RYAZHAPOVILNUR commented on src/app/store/users/users.actions.ts
> +
если запросов на бэкенд нету, то можно и не делать

2024-07-10 01:39 UTC, RYAZHAPOVILNUR commented on src/app/store/users/users.effects.ts
> +  );
у нас удаление редактирование добавление реализовано без бэкенда, так что эффекты для них не нужны

2024-07-11 08:45 UTC, Bolatzhan commented on src/app/services/local-storage.service.ts
> +
я его оставил из за того что я перед переписыванием на NGRX не коммитил

2024-07-11 08:46 UTC, Bolatzhan commented on src/app/services/users.service.ts
> +  private usersSubject$ = new BehaviorSubject<User[]>([]);
я его оставил из за того что я перед переписыванием на NGRX не коммитил

2024-07-18 14:22 UTC, closed without merging