Задание Джун(Дени/@v6_ars)
RYAZHAPOVILNUR/mentoring-first-task pull request #43
Opened 2024-07-20 15:35 UTC by Bardooo

2024-07-22 11:51 UTC, RYAZHAPOVILNUR requested changes

2024-07-22 11:51 UTC, RYAZHAPOVILNUR commented on src/app/components/create-edit-user/create-edit-user.component.ts
> +    id: this.randomInteger(1, 1000),
айдишники ведь будут повторяться потом

2024-07-23 06:47 UTC, Bardooo commented on src/app/components/create-edit-user/create-edit-user.component.ts
> +    id: this.randomInteger(1, 1000),
исправил

2024-07-23 12:39 UTC, RYAZHAPOVILNUR approved these changes

2024-07-23 12:39 UTC, closed without merging