Adam
RYAZHAPOVILNUR/mentoring-first-task pull request #94
Opened 2024-12-09 17:55 UTC by adam-qt

2024-12-10 14:22 UTC, adam-qt commented
last version

2024-12-11 12:16 UTC, adam-qt commented
telegram @adam_qt

2024-12-19 17:00 UTC, anatolyeviich requested changes
Нужно переписывать много чего

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/services/users.service.ts
> +};
Удалить комментарии. Почему тип находится в сервисе?

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/services/users.service.ts
> +}
Удалить

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/services/users.service.ts
> +  }
Для чего нужен этот метод, и почему здесь any?

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/services/users.service.ts
> +    };
Этот метод для чего? Для создания, для редактирования? Для того и того?

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/services/users-api.service.ts
> +  }
лучше назвать  http client и типизировать. Что за типизация object? Здесь должен быть интерфейс User

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/services/local-storage.service.ts
> +  }
local storage не должен содержать конкретной реализации

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/users-list/users-list.component.ts
> +
Протипизировать

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/users-list/users-list.component.ts
> +      });
Протипизировать

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/users-list/users-list.component.ts
> +  }
Инджектим с помощью функции inject, а не конструктора

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/users-list/users-list.component.html
> +
Форматирование
Почему user_item? Можно просто user

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/users-filter/users-filter.component.ts
> +  }
Что за компонент? Что он фильтрует?

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/edit-user-dialog/edit-user-dialog.component.ts
> +      ),
Форм группа должна соответствовать интерфейсу. Значит нам нужно создать форм группу (company) для name

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/edit-user-dialog/edit-user-dialog.component.ts
> +};
Это что за тип? Зачем он здесь?

2024-12-19 17:00 UTC, anatolyeviich commented on src/app/users/components/edit-user-dialog/edit-user-dialog.component.html
> +  <button type="submit"  style = "margin-top: 30px; margin-bottom: 20px" [disabled]="form.invalid" [mat-dialog-close]="userWithUpdatedFields" >{{ isEdit ? 'Edit' : 'Create' }}</button>
Нельзя привязывать  директиву mat-dialog-close к геттеру

2024-12-22 20:25 UTC, pocahontassss approved these changes

2024-12-22 20:25 UTC, pocahontassss commented on src/app/users/services/httpClientService.ts
Правильно назвать  userApiService, как и было до этого

2024-12-22 20:25 UTC, closed without merging